#!/usr/bin/env python3
"""
Create GitHub Issues for unfixable vulnerabilities from Black Duck report.

This script identifies vulnerabilities that lack a recommended_version or fixed_versions
and generates shell commands to create GitHub Issues using the GitHub CLI.

Usage:
    python3 security-tooling/create_github_issues.py
"""

import json
import sys
import os


def is_unfixable(vuln):
    """Check if a vulnerability has no fix available"""
    recommended_version = vuln.get('recommended_version')
    fixed_versions = vuln.get('fixed_versions', [])
    
    # No fix if both are missing/empty
    if not recommended_version and (not fixed_versions or len(fixed_versions) == 0):
        return True
    
    # Also check for explicit empty/null values
    if recommended_version in [None, '', 'unknown'] and (not fixed_versions or fixed_versions == []):
        return True
    
    return False


def generate_issue_body(vuln):
    """Generate GitHub Issue body in markdown format"""
    component = vuln.get('component', 'Unknown')
    version = vuln.get('version', 'Unknown')
    cve = vuln.get('vulnerability_id', 'UNKNOWN')
    severity = vuln.get('severity', 'UNKNOWN')
    cvss_score = vuln.get('cvss_score', 'N/A')
    description = vuln.get('description', 'No description available')
    ecosystem = vuln.get('ecosystem', 'unknown')
    file_path = vuln.get('file_path', 'Unknown')
    remediation = vuln.get('remediation', 'No remediation available')
    published_date = vuln.get('published_date', 'Unknown')
    
    body = f"""## 🚨 Unfixable Vulnerability Detected

**This vulnerability currently has NO available fix.** This issue has been automatically created by the Black Duck security scanner.

### Vulnerability Details

- **CVE ID**: {cve}
- **Severity**: {severity}
- **CVSS Score**: {cvss_score}
- **Published**: {published_date}

### Affected Component

- **Package**: `{component}`
- **Current Version**: `{version}`
- **Ecosystem**: {ecosystem}
- **File**: `{file_path}`

### Description

{description}

### Remediation Status

⚠️ **No fix currently available**

{remediation}

### Recommended Actions

1. **Monitor** vendor security announcements for updates
2. **Review** if this component is critical to your application
3. **Consider** alternative packages or workarounds
4. **Assess** the risk and potential impact on your systems
5. **Implement** additional security controls or network-level mitigations if possible

### Additional Information

- This issue will be automatically updated when a fix becomes available
- Subscribe to this issue for notifications
- Contact your security team for risk assessment

---

**Automated by Black Duck Security Scanner**  
Report Date: {vuln.get('scan_date', 'Unknown')}
"""
    
    return body


def main():
    print("=" * 70)
    print("GITHUB ISSUE CREATOR FOR UNFIXABLE VULNERABILITIES")
    print("=" * 70)
    print()
    
    # Load Black Duck report
    report_file = "security-tooling/mockBlackDuck/blackduck_report.json"
    try:
        with open(report_file, 'r') as f:
            report = json.load(f)
    except FileNotFoundError:
        print(f"❌ Error: {report_file} not found")
        sys.exit(1)
    
    vulnerabilities = report.get('vulnerabilities', [])
    
    # Find unfixable vulnerabilities
    unfixable_vulns = [v for v in vulnerabilities if is_unfixable(v)]
    
    if not unfixable_vulns:
        print("✅ No unfixable vulnerabilities found!")
        return 0
    
    print(f"⚠️  Found {len(unfixable_vulns)} unfixable vulnerability(ies)\n")
    
    # Generate output file with issue creation commands
    output_file = "security-tooling/generated/github-issues.sh"
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Generate JSON file with issue data for workflow
    issues_data_file = "security-tooling/generated/unfixable-vulnerabilities.json"
    issues_data = []
    
    with open(output_file, 'w') as f:
        f.write("#!/bin/bash\n")
        f.write("# Auto-generated script to create GitHub Issues for unfixable vulnerabilities\n")
        f.write("# Generated by security-tooling/create_github_issues.py\n\n")
        f.write("set -e\n\n")
        
        for idx, vuln in enumerate(unfixable_vulns, 1):
            cve = vuln.get('vulnerability_id', 'UNKNOWN')
            severity = vuln.get('severity', 'UNKNOWN')
            component = vuln.get('component', 'Unknown')
            
            print(f"{idx}. {cve} ({severity}) - {component}")
            print(f"   No fix available")
            
            # Generate issue title
            title = f"[Security] {cve} ({severity}): No fix available for {component}"

            # Generate labels
            labels = ["security", "unfixable", "blackduck", severity.lower() + "-priority"]
            if vuln.get('ecosystem'):
                labels.append(vuln.get('ecosystem'))
            labels_str = ",".join(labels)

            # Generate issue body
            body = generate_issue_body(vuln)

            # Write body to temp file (for gh cli)
            body_file = f"security-tooling/generated/issue-body-{idx}.md"
            with open(body_file, 'w') as bf:
                bf.write(body)

            # Store issue data
            issues_data.append({
                "cve": cve,
                "severity": severity,
                "component": component,
                "title": title,
                "labels": labels,
                "body_file": body_file
            })

            # Write gh command to script
            f.write(f"# Issue {idx}: {cve}\n")
            f.write(f"echo 'Creating issue for {cve}...'\n")
            f.write(f"gh issue create \\\n")
            f.write(f'  --title "{title}" \\\n')
            f.write(f'  --body-file "{body_file}" \\\n')
            f.write(f'  --label "{labels_str}"\n\n')

    # Make script executable
    os.chmod(output_file, 0o755)

    # Write issues data JSON
    with open(issues_data_file, 'w') as f:
        json.dump({
            "unfixable_count": len(unfixable_vulns),
            "issues": issues_data
        }, f, indent=2)

    print()
    print("=" * 70)
    print(f"✅ Generated GitHub Issue creation script: {output_file}")
    print(f"✅ Generated issue data: {issues_data_file}")
    print(f"✅ Total unfixable vulnerabilities: {len(unfixable_vulns)}")
    print("=" * 70)
    print()
    print("To create the issues, run:")
    print(f"  bash {output_file}")
    print()
    print("Or in GitHub Actions, the workflow will run this automatically.")

    return 0


if __name__ == "__main__":
    sys.exit(main())

